### PR TITLE
coreos-teardown-initramfs: ignore lo.nmconnection

### LINKED ISSUE #1385: kola: rawhide: `no-default-initramfs-net-propagation` test failures; unexpected `lo.nmconnection`
The `ext.config.networking.no-default-initramfs-net-propagation` test started failing in our cloud tests:

```
=== RUN   non-exclusive-test-bucket-0/ext.config.networking.no-default-initramfs-net-propagation.default
systemctl status kola-runext-40.service:
�� kola-runext-40.service
     Loaded: loaded (/etc/systemd/system/kola-runext-40.service; static)
     Active: failed (Result: exit-code) since Tue 2023-01-17 14:49:18 UTC; 1s ago
   Duration: 44ms
    Process: 1954 ExecStart=/usr/local/bin/kola-runext-default (code=exited, status=1/FAILURE)
   Main PID: 1954 (code=exited, status=1/FAILURE)
        CPU: 20ms

Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 systemd[1]: Started kola-runext-40.service.
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: + . /var/opt/kola/extdata-40/commonlib.sh
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: ++ cmdline=($(< /proc/cmdline))
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: + . /var/opt/kola/extdata-40/test-net-propagation.sh
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1956]: ++ grep 'info: skipping propagation of default networking configs'
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1955]: ++ journalctl -t coreos-teardown-initramfs
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: ++ echo 'no log message claiming to skip initramfs network propagation'
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: no log message claiming to skip initramfs network propagation
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: ++ fail=1
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1957]: +++ ls -A /etc/NetworkManager/system-connections/
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: ++ '[' -n 'default_connection.nmconnection
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: lo.nmconnection' ']'
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: ++ echo 'configs exist in /etc/NetworkManager/system-connections/, but shouldn'\''t'
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: configs exist in /etc/NetworkManager/system-connections/, but shouldn't
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: ++ fail=1
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1958]: +++ ls -A -I readme-ifcfg-rh.txt /etc/sysconfig/network-scripts/
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: ++ '[' -n '' ']'
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: + '[' -z 1 ']'
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: + fatal 'fail: no initramfs network propagation for default configuration'
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: + echo 'fail: no initramfs network propagation for default configuration'
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: fail: no initramfs network propagation for default configuration
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 kola-runext-default[1954]: + exit 1
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 systemd[1]: kola-runext-40.service: Main process exited, code=exited, status=1/FAILURE
Jan 17 14:49:18 kola-06adffb6e2fbb42f01b7 systemd[1]: kola-runext-40.service: Failed with result 'exit-code'.
--- FAIL: non-exclusive-test-bucket-0 (73.77s)
    --- FAIL: non-exclusive-test-bucket-0/ext.config.networking.no-default-initramfs-net-propagation.default (4.37s)
```

There is an unexpected `lo.nmconnection` file that is throwing off our "default NM configuration" check and causing initramfs networking to get propagated into the real root.

This started happening with `38.20230117.91.0` on our `rawhide` stream that includes `NetworkManager-1.41.8-1.fc38`.

### PR DESCRIPTION
**Pull request by dustymabe**
There are a few commits in here, but the most important is the reworking of `coreos-teardown-initramfs` to ignore the `lo.nmconnection`, which should fix https://github.com/coreos/fedora-coreos-tracker/issues/1385.

```
commit 6b1923264cde0b1f38faa9432a7721fa7a99c46c
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Tue Jan 17 17:02:21 2023 -0500

    tests: set rd.neednet=1 in bootif net propagation test
    
    Normally on qemu networking isn't brought up in the initramfs because
    it's not needed (the Ignition config is passed via fw_cfg, not network).
    This will force networking to be brought up to verify that bringing up
    NetworkManager doesn't materially change things.
    
    One case where it did materially change things and we needed to adapt
    is described in https://github.com/coreos/fedora-coreos-tracker/issues/1385

commit 6fb18ac9b3aa6a7531a14c660a425c4c2eab969d
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Tue Jan 17 17:01:02 2023 -0500

    tests: update comment in bootif net propagation test
    
    This improves the accuracy of the comment since we're forced to
    use qemu because the features we need aren't available on other
    platforms.

commit 6d79119b741ab8601cca88413a93d6d7c8de0c3a
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Tue Jan 17 16:57:33 2023 -0500

    coreos-teardown-initramfs: ignore lo.nmconnection
    
    Upstream NetworkManager now autogenerates a lo.nmconnection connection
    to manage the local loopback device. Let's ignore that connection for
    the purposes of our comparison and propagation here.
    
    Closes https://github.com/coreos/fedora-coreos-tracker/issues/1385

commit 737ca288d58a4b8d8756536270ac53584a78ed29
Author: Dusty Mabe <dusty@dustymabe.com>
Date:   Tue Jan 17 16:56:01 2023 -0500

    coreos-teardown-initramfs: fix spelling error

```

### CODE REVIEW

**Review by cgwalters — DISMISSED** [review]

File: overlay.d/05core/usr/lib/dracut/modules.d/35coreos-ignition/coreos-teardown-initramfs.sh [hunk 1]
```diff
@@ -127,6 +130,9 @@ propagate_initramfs_networking() {
             else
                 echo "info: propagating initramfs networking config to the real root"
                 cp -v /run/NetworkManager/system-connections/* /sysroot/etc/NetworkManager/system-connections/
+                # Delete lo.nmconnection if it was created.
+                # https://github.com/coreos/fedora-coreos-tracker/issues/1385
+                rm -f /sysroot/etc/NetworkManager/system-connections/lo.nmconnection
```
Comment (jlebon) [inline overlay.d/05core/usr/lib/dracut/modules.d/35coreos-ignition/coreos-teardown-initramfs.sh]: Minor: the previous `cp` runs with `-v` and so will print that it's copying `lo.nmconnection` which might be confusing since we delete it right after. I think it'd be cleaner to not copy it at all to begin with. I guess we could do that with a fancy `find` command, but maybe simpler to just add a `-v` to this so it's also logged that we deleted it.

**Review by jlebon — DISMISSED** [review]

File: overlay.d/05core/usr/lib/dracut/modules.d/35coreos-ignition/coreos-teardown-initramfs.sh (hunk 1 above)
Comment (dustymabe) [reply overlay.d/05core/usr/lib/dracut/modules.d/35coreos-ignition/coreos-teardown-initramfs.sh]: done!

**Review by jlebon — APPROVED** [review]
