### PR TITLE
tests/kola/toolbox: Retry 'toolbox create' to avoid infra flakes

### LINKED ISSUE #788: kola flake: FAIL: ext.config.toolbox
Seen in https://github.com/ostreedev/ostree/pull/2327
```
[2021-04-08T14:15:25.806Z] Apr 08 14:15:12 qemu0 systemd[1]: Started kola-runext.service.
[2021-04-08T14:15:25.806Z] Apr 08 14:15:12 qemu0 kola-runext-test.sh[1222]: + machinectl shell core@ /bin/toolbox create --assumeyes
[2021-04-08T14:15:25.806Z] Apr 08 14:15:12 qemu0 kola-runext-test.sh[1223]: Connected to the local host. Press ^] three times within 1s to exit session.
[2021-04-08T14:15:25.806Z] Apr 08 14:15:24 qemu0 kola-runext-test.sh[1223]: Connection to the local host terminated.
[2021-04-08T14:15:25.806Z] Apr 08 14:15:24 qemu0 kola-runext-test.sh[1357]: ++ grep --count fedora-toolbox-
[2021-04-08T14:15:25.806Z] Apr 08 14:15:24 qemu0 kola-runext-test.sh[1356]: ++ machinectl shell core@ /bin/toolbox list --containers
[2021-04-08T14:15:25.06Z] Apr 08 14:15:24 qemu0 kola-runext-test.sh[1356]: Connected to the local host. Press ^] three times within 1s to exit session.
[2021-04-08T14:15:25.806Z] Apr 08 14:15:24 qemu0 kola-runext-test.sh[1356]: Connection to the local host terminated.
[2021-04-08T14:15:25.806Z] Apr 08 14:15:24 qemu0 kola-runext-test.sh[1222]: + [[ 0 -ne 1 ]]
[2021-04-08T14:15:25.807Z] Apr 08 14:15:24 qemu0 kola-runext-test.sh[1222]: + fatal 'Could not create toolbox'
[2021-04-08T14:15:25.807Z] Apr 08 14:15:24 qemu0 kola-runext-test.sh[1222]: + echo 'Could not create toolbox'
[2021-04-08T14:15:25.807Z] Apr 08 14:15:24 qemu0 kola-runext-test.sh[1222]: Could not create toolbox
[2021-04-08T14:15:25.807Z] Apr 08 14:15:24 qemu0 kola-runext-test.sh[1222]: + exit 1
[2021-04-08T14:15:25.807Z] Apr 08 14:15:24 qemu0 systemd[1]: kola-runext.service: Main process exited, code=exited, status=1/FAILURE
[2021-04-08T14:15:25.807Z] Apr 08 14:15:24 qemu0 systemd[1]: kola-runext.service: Failed with result 'exit-code'.
[2021-04-08T14:15:27.181Z] --- PASS: ext.ostree.nondestructive.itest-payload-link.sh (166.88s)
[2021-04-08T14:15:28.126Z] --- FAIL: ext.config.toolbox (49.58s)
[2021-04-08T14:15:28.126Z]         harness.go:714: kolet failed: : kolet run-test-unit failed: Error: Unit kola-runext.service exited with code 1
```

### PR DESCRIPTION
**Pull request by travier**
Retry to create the toolbox container five times to avoid failing on
Fedora registry infra flakes.

Fixes: https://github.com/coreos/fedora-coreos-tracker/issues/788

### CODE REVIEW

File: tests/kola/toolbox/test.sh [hunk 1]
```diff
@@ -25,7 +25,15 @@ fatal() {
     exit 1
 }
 
-machinectl shell core@ /bin/toolbox create --assumeyes 1>/dev/null
+# Try five times to create the toolbox to avoid Fedora registry infra flakes
+for i in $(seq 1 5); do
+	machinectl shell core@ /bin/toolbox create --assumeyes 1>/dev/null
+	if [[ $(machinectl shell core@ /bin/toolbox list --containers | grep --count fedora-toolbox-) -ne 1 ]]; then
+		echo "Could not create toolbox on try: $i"
```
Comment (dustymabe) [inline tests/kola/toolbox/test.sh:32]: should we sleep in between any amount of time?

**Comment by travier** [comment]
Updated. Thanks!

**Review by lucab — APPROVED** [review]
