### PR TITLE
overlay: 40ignition-ostree: make ignition-ostree-transposefs tolerant to debug kernels

### LINKED ISSUE #1092: rawhide: kola: 20220205: `coreos.boot-mirror.luks` test enters emergency.target
The `coreos.boot-mirror.luks` just started failing semi consistently in the `rawhide` stream. We first [saw it in CI](https://github.com/coreos/fedora-coreos-config/pull/1486#issuecomment-1030738946) and now it's happening in the pipeline [fedora-coreos-pipeline#19](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/fedora-coreos-pipeline/job/fedora-coreos-pipeline-fedora-coreos-pipeline/19). Cracking open the `console.txt` for the test shows us:

```
  106.786833] systemd[1]: ignition-ostree-uuid-root.service - Ignition OSTree: Regenerate Filesystem UUID (root) was skipped because of a failed c
[  106.816385] systemd[1]: Starting ignition-ostree-transposefs-restore.service - Ignition OSTree: Restore Partitions...^M
         Starting ^[[0;1;39mignition-ostree-t…tion OSTree: Restore Partitions...^M
[  106.873485] ignition-ostree-transposefs[1852]: Restoring rootfs from RAM...^M
[  106.983108] ignition-ostree-transposefs[1856]: realpath: /dev/disk/by-label/root: No such file or directory^M
[  106.991587] systemd[1]: ignition-ostree-transposefs-restore.service: Main process exited, code=exited, status=1/FAILURE^M
[  106.994594] systemd[1]: ignition-ostree-transposefs-restore.service: Failed with result 'exit-code'.^M
[  106.999748] systemd[1]: Failed to start ignition-ostree-transposefs-restore.service


```

Full console.txt file: [coreos-boot-mirror-luks-console.txt](https://github.com/coreos/fedora-coreos-tracker/files/8011313/coreos-boot-mirror-luks-console.txt)

### PR DESCRIPTION
**Pull request by dustymabe**
It appears that on debug kernels the "/dev/disk/by-label/$label" device *can* not
appear at all (some sort of race condition) and thus calling `realpath` on it will
fail. Let's just make the call to `realpath` not be fatal so we can workaround this
issue that has been around in the kernel for some time.

Closes https://github.com/coreos/fedora-coreos-tracker/issues/1092

### CODE REVIEW

File: overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/ignition-ostree-transposefs.sh [hunk 1]
```diff
@@ -56,7 +56,10 @@ udev_trigger_on_label_mismatch() {
     local expected_dev=$1; shift
     local actual_dev
     expected_dev=$(realpath "${expected_dev}")
-    actual_dev=$(realpath "/dev/disk/by-label/$label")
+    # We `|| :` here because sometimes /dev/disk/by-label/$label is missing.
+    # We've seen this on Fedora kernels with debug enabled (common in `rawhide`).
+    # See https://github.com/coreos/fedora-coreos-tracker/issues/1092
```
Comment (jlebon) [inline overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/ignition-ostree-transposefs.sh:61]: Would've been nice to see an RHBZ here instead of/in addition to the tracker issue, but OK as is too.

**Review by jlebon — APPROVED** [review]

**Comment by cgwalters** [comment]
Wait isn't it that debug kernels are going to be much slower?  If this is truly racy then it seems like we shouldn't ignore the failure entirely...

The BZ linked above talks about systemd, not the kernel?

**Comment by dustymabe** [comment]
@cgwalters - maybe let's take the discussion to https://github.com/coreos/fedora-coreos-tracker/issues/1092
