### PR TITLE
35coreos-ignition: perform kargs reboot with `--force`

### LINKED ISSUE #896: reduce logging noise when using ignition-kargs
Right now when you use the [ignition kargs feature](https://docs.fedoraproject.org/en-US/fedora-coreos/kernel-args/#_modifying_kernel_arguments_via_ignition) if you watch the console logs you might be alarmed. There are a lot of "failures" that scroll by as it goes down for reboot after applying the kernel arguments. This might be alarming, but I think it's harmless (though it's hard to be sure).

Here is one example:

<details>

```
[    2.704117] systemd[1]: Condition check resulted in Ignition (fetch) being skipped.
         Startin[    2.704774] systemd[1]: Starting Ignition (kargs)...
g Ignition (kargs)...
         Starting Ignit[    2.706949] systemd[1]: Starting Ignition OSTree: Detect Partition Transposition...
ion OSTree: …ect Partition Transposition...
<info>  [1625848758.2856] manager[0x5641c72e80c0]: monitoring kernel firmware directory '/lib/firmware'.
         Starting nm-wait-online-initrd.service...
[    2.715850] NetworkManager[515]: <info>  [1625848758.2856] manager[0x5641c72e80c0]: monitoring kernel firmware directory '/lib/firmware'.
[    2.716799] systemd[1]: Starting nm-wait-online-initrd.service...
[    2.719775] ignition[520]: Ignition 2.11.0
[    2.720134] ignition[520]: Stage: kargs
[    2.720474] ignition[520]: reading system config file "/usr/lib/ignition/base.d/00-core.ign"
[    2.721177] ignition[520]: reading system config file "/usr/lib/ignition/base.d/30-afterburn-sshkeys-core.ign"
[    2.721991] ignition[520]: no config dir at "/usr/lib/ignition/base.platform.d/qemu"
[    2.722601] ignition[520]: kargs: op(1): [started]  updating kernel arguments
<info>  [1625848758.3006] hostname: hostname: couldn't get property from hostnamed
[    2.725367] NetworkManager[515]: <info>  [1625848758.3006] hostname: hostname: couldn't get property from hostnamed
<info>  [1625848758.3014] dns-mgr[0x5641c72db110]: init: dns=default,systemd-resolved rc-manager=symlink (auto)
[    2.727053] NetworkManager[515]: <info>  [1625848758.3014] dns-mgr[0x5641c72db110]: init: dns=default,systemd-resolved rc-manager=symlink (auto)
<info>  [1625848758.3092] manager[0x5641c72e80c0]: rfkill: Wi-Fi hardware radio set enabled[    2.733873] EXT4-fs (sda3): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.

[    2.734593] ext4 filesystem being mounted at /tmp/coreos-installer-TXxRmN supports timestamps until 2038 (0x7fffffff)
<info>  [1625848758.3104] manager[0x5641c72e80c0]: rfkill: WWAN [    2.735704] NetworkManager[515]: <info>  [1625848758.3092] manager[0x5641c72e80c0]: rfkill: Wi-Fi hardware radio set enabled
hardware radio set enabled
[    2.737474] NetworkManager[515]: <info>  [1625848758.3104] manager[0x5641c72e80c0]: rfkill: WWAN hardware radio set enabled
<info>  [1625848758.3148] Loaded device plugin: NMTeamFactory (/usr/lib64/NetworkManager/1.30.4-1.fc34/libnm-device-plugin-team.so)
<info>  [1625848[    2.739996] NetworkManager[515]: <info>  [1625848758.3148] Loaded device plugin: NMTeamFactory (/usr/lib64/NetworkManager/1.30.4-1.fc34/libnm-device-plugin-team.so)
758.3158] manager: rfkill: Wi-Fi enabled by radio killswitch; enabled by state file
<info>  [1625848758.3176] manage[    2.741957] NetworkManager[515]: <info>  [1625848758.3158] manager: rfkill: Wi-Fi enabled by radio killswitch; enabled by state file
r: rfkill: WWAN enabled by radio killswitch; enabled by state file
[    2.743434] NetworkManager[515]: <info>  [1625848758.3176] manager: rfkill: WWAN enabled by radio killswitch; enabled by state file
<info>  [1625848758.3193] manager: Networking is enabled by state file
<info>  [1625848758.3205] dhcp-i[    2.744913] NetworkManager[515]: <info>  [1625848758.3193] manager: Networking is enabled by state file
nit: Using DHCP client 'internal'
[    2.746053] NetworkManager[515]: <info>  [1625848758.3205] dhcp-init: Using DHCP client 'internal'
<info>  [1625848758.3219] settings: Loaded settings plugin: keyfile (internal)
<warn>  [1625848[    2.747241] NetworkManager[515]: <info>  [1625848758.3219] settings: Loaded settings plugin: keyfile (internal)
758.3230] settings: could not load plugin 'ifcfg-rh' from file '/usr/lib64/NetworkManager/1.30.4-1.fc34/libnm-settings-plugin-ifcfg-rh.so': No such file or directory
[    2.749148] NetworkManager[515]: <warn>  [1625848758.3230] settings: could not load plugin 'ifcfg-rh' from file '/usr/lib64/NetworkManager/1.30.4-1.fc34/libnm-settings-plugin-ifcfg-rh.so': No such file or directory
<info>  [1625848758.3268] device (lo): carrier: link connected
[    2.751468] NetworkManager[515]: <info>  [1625848758.3268] device (lo): carrier: link connected
<info>  [1625848758.3274] manager: (lo): new Generic device (/org/freedesktop/NetworkManager/Devices/1)
[    2.753452] NetworkManager[515]: <info>  [1625848758.3274] manager: (lo): new Generic device (/org/freedesktop/NetworkManager/Devices/1)
<info>  [1625848758.3299] manager: (ens2): new Ethernet device (/org/freedesktop/NetworkManager/Devices/2)
<info>  [1625848758.3314] device (ens2): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
[    2.756453] NetworkManager[515]: <info>  [1625848758.3299] manager: (ens2): new Ethernet device (/org/freedesktop/NetworkManager/Devices/2)
[    2.758674] e1000: ens2 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[    2.758891] NetworkManager[515]: <info>  [1625848758.3314] device (ens2): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
[    2.759819] IPv6: ADDRCONF(NETDEV_CHANGE): ens2: link becomes ready
<info>  [1625848758.3383] manager: (ens3): new Ethernet device (/org/freedesktop/NetworkManager/Devices/3)
<info>  [1625848758.3395] device (ens3): state c[    2.764013] NetworkManager[515]: <info>  [1625848758.3383] manager: (ens3): new Ethernet device (/org/freedesktop/NetworkManager/Devices/3)
hange: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
[    2.767477] ignition[520]: kargs: op(1): [finished] updating kernel arguments
[    2.767994] e1000: ens3 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[  OK  ] Finished     2.769121] IPv6: ADDRCONF(NETDEV_CHANGE): ens3: link becomes ready
;1;39mIgnition (kargs).
[    2.770018] NetworkManager[515]: <info>  [1625848758.3395] device (ens3): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
[    2.771112] ignition[520]: kargs: kargs passed
[    2.771128] systemd[1]: Finished Ignition (kargs).
[    2.771157] ignition[520]: Ignition finished successfully
[    2.771170] systemd[1]: Starting CoreOS Kernel Arguments Reboot...
         Starting CoreOS Kernel Arguments Reboot...
[    2.775587] systemctl[539]: Failed to set wall message, ignoring: The name is not activatable
<info>  [1625848758.3516] manager: (team0): new Team device (/org/freedesktop/NetworkManager/Devices/4)[    2.776826] systemctl[539]: Failed to reboot system via logind: The name is not activatable

[    2.780441] NetworkManager[515]: <info>  [1625848758.3516] manager: (team0): new Team device (/org/freedesktop/NetworkManager/Devices/4)
[    2.783750] systemd[1]: Finished CoreOS Kernel Arguments Reboot.
[  OK  ] Finished CoreOS Kernel Arguments Reboot.
[  OK      2.785267] systemd[1]: Stopped target Network.
0m] Stopped target Network.
[  OK      2.786111] systemd[1]: Stopped target Timers.
0m] Stopped target Timers.
[  OK      2.786919] systemd[1]: Reached target Unmount All Filesystems.
0m] Reached target Unmount All Filesystems.
[  OK      2.788023] systemd[1]: Stopped target Basic System.
0m] Stopped target Basic System.
[  OK      2.788919] systemd[1]: Stopped target Paths.
0m] Stopped target Paths.
[  OK      2.789705] systemd[1]: Stopped target Slices.
0m] Stopped target Slices.
[  OK      2.790498] systemd[1]: Stopped target Sockets.
0m] Stopped target Sockets.
         Stopping D-Bus System Message Bus...[    2.792113] dbus-broker[518]: Dispatched 389 messages @ 1(±2)μs / message.

[    2.793034] systemd[1]: Stopping D-Bus System Message Bus...
<info>  [1625848758.3754] device (team0): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')
[    2.793477] systemd[1]: Condition check resulted in Clear SSSD NSS cache in persistent /var being skipped.
Daemon not running

(NetworkManager:515): GLib-GIO-CRITICAL **: 16:39:18.378: Error while sending AddMatch() message: The connection is closed

(NetworkManager:515): GLib-GIO-CRITICAL **: 16:39:18.379: Error while sending AddMatch() message: The connection is closed

(NetworkManager:515): GLib-GIO-CRITICAL **: 16:39:18.380: Error while sending AddMatch() message: The connection is closed
<warn>  [1625848758.3815] sleep-monitor-sd: failed to acquire D-Bus proxy: The connection is closed

(NetworkManager:515): GLib-GIO-CRITICAL **: 16:39:18.383: g_dbus_connection_call_finish_internal: assertion 'G_IS_DBUS_CONNECTION (connection)' failed[    2.793507] systemd[1]: Stopping CoreOS Tear Down Initramfs...
[    2.800403] NetworkManager[515]: <info>  [1625848758.3754] device (team0): state change: unmanaged -> unavailable (reason 'managed', sys-iface-state: 'external')

<info>  [1625848758.3876] device (ens2): carrier: link connected
<info>  [1625848758.3882] device (ens3): carrier: link connected[    2.805678] systemd-udevd[440]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.

<info>  [1625848758.3899] device (ens2): state change: unavailable -> disconnected (reason 'carrier-changed', sys-iface-state: 'managed')[    2.807930] NetworkManager[515]: <warn>  [1625848758.3815] sleep-monitor-sd: failed to acquire D-Bus proxy: The connection is closed

[    2.812287] NetworkManager[515]: <info>  [1625848758.3876] device (ens2): carrier: link connected
[    2.814511] coreos-teardown-initramfs[545]: info: taking down network device: ens2
         Stoppin[    2.814601] coreos-teardown-initramfs[559]: RTNETLINK answers: Operation not supported
g CoreO[    2.814621] NetworkManager[515]: <info>  [1625848758.3882] device (ens3): carrier: link connected
S Tear Down Init[    2.815965] NetworkManager[515]: <info>  [1625848758.3899] device (ens2): state change: unavailable -> disconnected (reason 'carrier-changed', sys-iface-state: 'managed')
ramfs...
[    2.820262] systemd[1]: Starting Populate OSTree /var...
         Starting Populate OSTree /var...
[    2.821099] systemd[1]: Condition check resulted in Acquire live PXE rootfs image being skipped.
[    2.821747] systemd[1]: Condition check resulted in Persist osmet files (PXE) being skipped.
[    2.821775] systemd[1]: dracut-pre-trigger.service: Deactivated successfully.
[    2.821832] systemd[1]: Stopped dracut pre-trigger hook.
[  OK  ] Stopped dracut pre-trigger hook.
[    2.824678] systemd[1]: dracut-pre-udev.service: Deactivated successfully.
[  OK      2.825277] systemd[1]: Stopped dracut pre-udev hook.
0m] Stopped dracut pre-udev hook.
[  OK  ] Stopped D-Bus Syste[    2.826725] systemd[1]: dbus-broker.service: Deactivated successfully.
m Message Bus.[    2.827408] systemd[1]: Stopped D-Bus System Message Bus.

[  OK  ] Stopped nm-wait-online-initrd.servi[    2.834044] ignition-ostree-populate-var[571]: cp: cannot stat '/sysroot/etc/skel/.bash*': No such file or directory
ce.
[    2.835058] systemd[1]: nm-wait-online-initrd.service: Deactivated successfully.
[    2.835768] systemd[1]: Stopped nm-wait-online-initrd.service.
[FAILED[    2.836307] systemd[1]: ignition-ostree-populate-var.service: Main process exited, code=exited, status=1/FAILURE
] Failed to start Populate OSTree /[    2.837392] systemd[1]: ignition-ostree-populate-var.service: Failed with result 'exit-code'.
var.
[    2.838242] systemd[1]: Failed to start Populate OSTree /var.
See 'systemctl status ignition-ostree-populate-var.service' for details.
[  OK      2.839822] systemd[1]: Stopped target System Initialization.
0m] Stopped target System Initialization.
[  OK  ] Stopped target Local Encrypted Volumes.
[    2.841700] systemd[1]: Stopped target Local Encrypted Volumes.
[    2.842169] systemd[1]: systemd-ask-password-console.path: Deactivated successfully.
[    2.842803] systemd[1]: Stopped Dispatch Password Requests to Console Directory Watch.
[  OK  ] Stopped Dispatch Password …ts to Console Directory Watch.
[    2.843885] systemd[1]: Stopped target Local Encrypted Volumes (Pre).
[  OK  ] Stopped target Local Encrypted Volumes (Pre).
[    2.844858] systemd[1]: Stopped target Local File Systems.
[  OK  ] Stopped target Local File Systems.
[    2.845738] systemd[1]: Stopped target Local File Systems (Pre).
[  OK  ] Stopped target Local File Systems (Pre).
[    2.846642] systemd[1]: Stopped target Swap.
[  OK  ] Stopped target Swap.
[    2.847855] systemd[1]: Starting Ignition (files)...
         Starting Ignition (files)...
[    2.848925] systemd[1]: Stopping Device-Mapper Multipath Device Controller...
         Stopping Device-Mapper Multipath Device Controller...
[    2.850013] systemd[1]: Stopping nm-initrd.service...
         Stopping nm-initrd.service...
[    2.850790] systemd[1]: systemd-sysctl.service: Deactivated successfully.
[    2.851398] systemd[1]: Stopped Apply Kernel Variables.
[  OK  ] Stopped Apply Kernel Variables.
[    2.852413] systemd[1]: systemd-modules-load.service: Deactivated successfully.
[    2.853069] systemd[1]: Stopped Load Kernel Modules.
[    2.853677] multipathd[575]: 2.815434 | /etc/multipath.conf does not exist, blacklisting all devices.
[    2.854486] multipathd[575]: 2.815442 | You can run "/sbin/mpathconf --enable" to create
[    2.855187] multipathd[575]: 2.815451 | /etc/multipath.conf. See man mpathconf(8) for more details
[  OK  ] Stopped Load Kernel Modules.
[    2.856475] systemd[1]: systemd-tmpfiles-setup-dev.service: Deactivated successfully.
[  OK  ] Stopped Create Static Device Nodes in /dev.
[    2.857664] systemd[1]: Stopped Create Static Device Nodes in /dev.
[    2.858306] multipathd[575]: ok
[    2.858578] multipathd[479]: --------shut down-------
[  OK  ] Stopped Create Volatile Files and Directories.
[    2.859644] systemd[1]: systemd-tmpfiles-setup.service: Deactivated successfully.
[    2.860262] systemd[1]: Stopped Create Volatile Files and Directories.
[  OK  ] Stopped Create System Users.
[    2.861258] systemd[1]: systemd-sysusers.service: Deactivated successfully.
[    2.861871] systemd[1]: Stopped Create System Users.
<info>  [1625848758.4413] device (ens3): state change: unavailable -> disconnected (reason 'carrier-changed', sys-iface-state: 'managed')
<info>  [1625848758.4427] device (team0): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'managed')
<info>  [1625848758.4435] caught SIGTERM, shutting down normally.
<info>  [1625848758.4490] exiting (success)
[    2.876751] coreos-teardown-initramfs[545]: info: taking down network device: ens3
[    2.877368] NetworkManager[515]: <info>  [1625848758.4413] device (ens3): state change: unavailable -> disconnected (reason 'carrier-changed', sys-iface-state: 'managed')
[  OK  ] Stopped Device-Mapper Multipath Device Controller.
[    2.879787] coreos-teardown-initramfs[583]: RTNETLINK answers: Operation not supported
[    2.880397] NetworkManager[515]: <info>  [1625848758.4427] device (team0): state change: unavailable -> disconnected (reason 'none', sys-iface-state: 'managed')
[  OK  ] Stopped nm-initrd.service.
[  OK  ] Closed D-Bus System Message Bus Socket.
[  OK  ] Reached target Shutdown.
[  OK  ] Reached target Final Step.
[    2.884846] ignition[574]: INFO     : Ignition 2.11.0
[    2.885234] ignition[574]: INFO     : Stage: files
[    2.885588] ignition[574]: INFO     : reading system config file "/usr/lib/ignition/base.d/00-core.ign"
[  OK  ] Stopped dracut cmdline hook.
[  OK  ] Stopped dracut ask for additional cmdline parameters.
[  OK  ] Finished Reboot.
[    2.888574] ignition[574]: DEBUG    : parsing config with SHA512: ff6a5153be363997e4d5d3ea8cc4048373a457c48c4a5b134a08a30aacd167c1e0f099f0bdf1e24c99ad180628cd02b767b863b5fe3a8fce3fe1886847eb8e2e
[  OK  ] Reached target Reboot.
[    2.891526] ignition[574]: INFO     : reading system config file "/usr/lib/ignition/base.d/30-afterburn-sshkeys-core.ign"
[    2.892460] ignition[574]: DEBUG    : parsing config with SHA512: a30a1921169d5a3b58ef9b25de60783be1add6ea8d05fd44a0746cb60dd1b8a8b34ab51eec5eb14eecc2df2ab6ba1cd3fd7351eed65793d22316ab262a857d95
[    2.893795] ignition[574]: INFO     : no config dir at "/usr/lib/ignition/base.platform.d/qemu"
[    2.894595] NetworkManager[515]: <info>  [1625848758.4435] caught SIGTERM, shutting down normally.
[    2.895348] ignition[574]: INFO     : files: ensureUsers: op(1): [started]  creating or modifying user "core"
[    2.896900] ignition[574]: DEBUG    : files: ensureUsers: op(1): executing: "useradd" "--root" "/sysroot" "--create-home" "--password" "*" "--comment" "CoreOS Admin" "--groups" "adm,sudo,systemd-journal,wheel" "core"
[    2.898352] ignition[574]: CRITICAL : files: ensureUsers: op(1): [failed]   creating or modifying user "core": exit status 10: Cmd: "useradd" "--root" "/sysroot" "--create-home" "--password" "*" "--comment" "CoreOS Admin" "--groups" "adm,sudo,systemd-journal,wheel" "core" Stdout: "" Stderr: "useradd: cannot lock /etc/group; try again later.\n"
[    2.901307] ignition[574]: files failed
[    2.901643] ignition[574]: Full config:
[    2.901985] ignition[574]: {
[    2.902253] ignition[574]:   "ignition": {
[    2.902614] ignition[574]:     "config": {
[    2.903053] ignition[574]:       "replace": {
[    2.903436] ignition[574]:         "verification": {}
[    2.903930] ignition[574]:       }
[    2.904239] ignition[574]:     },
[    2.904533] ignition[574]:     "proxy": {},
[    2.908853] systemd-shutdown[1]: Syncing filesystems and block devices.
[    2.909406] ignition[574]:     "security": {
[    2.909822] ignition[574]:       "tls": {}
[    2.910186] ignition[574]:     },
[    2.910505] ignition[574]:     "timeouts": {},
[    2.910969] ignition[574]:     "version": "3.4.0-experimental"
[    2.911478] ignition[574]:   },
[    2.911777] ignition[574]:   "kernelArguments": {
[    2.912190] ignition[574]:     "shouldExist": [
[    2.912592] ignition[574]:       "mitigations=off"
[    2.913060] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
[    2.915859] ignition[574]:     ],
[    2.916196] ignition[574]:     "shouldNotExist": [
[    2.916579] ignition[574]:       "mitigations=auto,nosmt"
[    2.917008] ignition[574]:     ]
[    2.917294] ignition[574]:   },
[    2.917565] ignition[574]:   "passwd": {
[    2.917936] ignition[574]:     "users": [
[    2.918324] ignition[574]:       {
[    2.918639] ignition[574]:         "gecos": "CoreOS Admin",
[    2.919146] ignition[574]:         "groups": [
[    2.919587] ignition[574]:           "adm",
[    2.920052] ignition[574]:           "sudo",
[    2.920464] ignition[574]:           "systemd-journal",
[    2.920960] ignition[574]:           "wheel"
[    2.921356] ignition[574]:         ],
[    2.921745] ignition[574]:         "name": "core",
[    2.922205] ignition[574]:         "sshAuthorizedKeys": [
[    2.922716] ignition[574]:           "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC90eJoqaj14TGhN4TdJU/f9GrlzNZ37ppNmqDnOfY+J68V4oCdxmXgRRAQzbMqdE6oqxpTY/BqPQWD4XcFte5wj9F5yn5L95pmcavH0ai9sh8bPf8u3akyq/oX+JnZ73JsZV+UUqfCns/k4RxnHjjbiXzTKqfXE01+z/tEiOgk7dQZ26dzO16KsnSgZQdS2EAxD6IZNPikGu4J3jfr2YA+ossx5tDLGw+924dCRDW/vCe2dGspONgyKRRVFk6L2iFJ1XLtP+PWyCZLxJ3GmRsC+1UgvpTI9iA2J+Ha4mOHwBBvpYtlvU/raXUl3+QPrlPGnwRapjSXPMvwtaFjZWWtX5u3HV9amBd6x9I18kIeScQ0VEoqW0tNi5HrpaZeHvJsFHmDeK0Q0/s6P1yPQeiDOzweCPz4sZHxeQ5jv+DHLK844nkGElwCFVc3/ffRcH0hhmJcTBrh3KqWpUi3w94mAz1m+Vfh2CxwEocx8ahv9Pv+UBBPRFSUZ8Qf1nXN8jc="
[    2.926817] ignition[574]:         ]
[    2.927125] ignition[574]:       }
[    2.927437] ignition[574]:     ]
[    2.927767] ignition[574]:   },
[    2.928087] ignition[574]:   "storage": {},
[    2.928484] ignition[574]:   "systemd": {
[    2.928866] ignition[574]:     "units": [
[    2.929221] ignition[574]:       {
[    2.929531] ignition[574]:         "enabled": true,
[    2.930744] ignition[574]:         "name": "afterburn-sshkeys@core.service"
[    2.931337] ignition[574]:       },
[    2.931632] ignition[574]:       {
[    2.931927] ignition[574]:         "dropins": [
[    2.932259] ignition[574]:           {
[    2.932712] NetworkManager[515]: <info>  [1625848758.4490] exiting (success)
[    2.933258] ignition[574]:             "contents": "[Service]\n# Override Execstart in main unit\nExecStart=\n# Add new Execstart with `-` prefix to ignore failure\nExecStart=-/usr/sbin/agetty --autologin core --noclear %I screen\nTTYVTDisallocate=no\n",
[    2.934991] ignition[574]:             "name": "autologin-core.conf"
[    2.935506] ignition[574]:           }
[    2.935841] ignition[574]:         ],
[    2.936159] ignition[574]:         "name": "serial-getty@ttyS0.service"
[    2.936698] ignition[574]:       }
[    2.936984] ignition[574]:     ]
[    2.937239] ignition[574]:   }
[    2.937497] ignition[574]: }CRITICAL : Ignition failed: failed to create users/groups: failed to configure users: failed to create user "core": exit status 10: Cmd: "useradd" "--root" "/sysroot" "--create-home" "--password" "*" "--comment" "CoreOS Admin" "--groups" "adm,sudo,systemd-journal,wheel" "core" Stdout: "" Stderr: "useradd: cannot lock /etc/group; try again later.\n"
[    2.940009] systemd[1]: multipathd.service: Deactivated successfully.
[    2.940491] systemd[1]: Stopped Device-Mapper Multipath Device Controller.
[    2.940989] systemd[1]: nm-initrd.service: Deactivated successfully.
[    2.941433] systemd[1]: Stopped nm-initrd.service.
[    2.941790] systemd[1]: dbus.socket: Deactivated successfully.
[    2.942259] systemd[1]: Closed D-Bus System Message Bus Socket.
[    2.942677] systemd[1]: Reached target Shutdown.
[    2.943032] systemd[1]: Reached target Final Step.
   The selected entry will be started automatically in 0s.
[    2.943892] systemd[1]: Stopped dracut cmdline hook.
[    2.944263] systemd[1]: dracut-cmdline-ask.service: Deactivated successfully.
[    2.944808] systemd[1]: Stopped dracut ask for additional cmdline parameters.
[    2.945370] systemd[1]: systemd-reboot.service: Deactivated successfully.
[    2.945931] systemd[1]: Finished Reboot.
[    2.946280] systemd[1]: Reached target Reboot.
[    2.946680] systemd[1]: Shutting down.
[    2.947043] systemd-journald[251]: Received SIGTERM from PID 1 (systemd-shutdow).
[    2.948092] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[    2.949612] systemd-shutdown[1]: Unmounting file systems.
[    2.950483] [591]: Remounting '/' read-only in with options 'size=1496876k,nr_inodes=374219,inode64'.
[    2.951276] systemd-shutdown[1]: All filesystems unmounted.
[    2.951766] systemd-shutdown[1]: Deactivating swaps.
[    2.952209] systemd-shutdown[1]: All swaps deactivated.
[    2.952676] systemd-shutdown[1]: Detaching loop devices.
[    2.953286] systemd-shutdown[1]: All loop devices detached.
[    2.953722] systemd-shutdown[1]: Stopping MD devices.
[    2.954144] systemd-shutdown[1]: All MD devices stopped.
[    2.954564] systemd-shutdown[1]: Detaching DM devices.
[    2.955002] systemd-shutdown[1]: All DM devices detached.
[    2.955413] systemd-shutdown[1]: All filesystems, swaps, loop devices, MD devices and DM devices detached.
[    2.956612] systemd-shutdown[1]: Syncing filesystems and block devices.
[    2.957124] systemd-shutdown[1]: Rebooting.
[    2.957473] sd 0:0:0:0: [sda] Synchronizing SCSI cache
[    2.988646] reboot: Restarting system
[    2.989016] reboot: machine restart
```

</details>

Of note in there I see things like `Ignition failed` with `useradd: cannot lock /etc/group; try again later` and also a `FAILURE` in `ignition-ostree-populate-var.service`.

Are these all harmless?  Can we do anything to clean this up?

### PR DESCRIPTION
**Pull request by bgilbert**
Without `--force`, the boot process races with service shutdown, leaving enough time for the disks stage to start.  With `--force`, systemd immediately kills processes, unmounts filesystems, and reboots.

xref https://github.com/coreos/ignition/pull/1252 upstream.

Fixes https://github.com/coreos/fedora-coreos-tracker/issues/896.

### CODE REVIEW

**Comment by dustymabe** [comment]
I assume this might intersect with https://github.com/coreos/fedora-coreos-tracker/issues/896 ?

File: overlay.d/05core/usr/lib/dracut/modules.d/35coreos-ignition/coreos-kargs-reboot.service [hunk 1]
```diff
@@ -18,4 +18,4 @@ OnFailureJobMode=isolate
 [Service]
 Type=oneshot
 RemainAfterExit=yes
-ExecStart=/usr/bin/systemctl reboot
```
Comment (dustymabe) [inline overlay.d/05core/usr/lib/dracut/modules.d/35coreos-ignition/coreos-kargs-reboot.service:21]: might be nice to have a comment here in the code mentioning why force is useful (without someone having to peruse commit messages).

**Review by dustymabe — DISMISSED** [review]
LGTM

**Review by jlebon — DISMISSED** [review]
Yeah, this should fix https://github.com/coreos/fedora-coreos-tracker/issues/896.

Checking CI results from `ext.config.ignition.kargs`:

```
[    5.086801] systemd[1]: Starting CoreOS Kernel Arguments Reboot...
[    5.088409] ignition[503]: Ignition finished successfully
[    5.090635] systemd[1]: Shutting down.
[    5.113581] systemd-shutdown[1]: Syncing filesystems and block devices.
[    5.115764] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
[    5.120721] multipathd[467]: exit (signal)
[    5.121896] multipathd[467]: --------shut down-------
[    5.126648] systemd-journald[256]: Received SIGTERM from PID 1 (systemd-shutdow).
[    5.140963] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[    5.144599] systemd-shutdown[1]: Unmounting file systems.
[    5.146761] [540]: Remounting '/' read-only in with options 'size=450108k,nr_inodes=112527,inode64'.
[    5.149223] systemd-shutdown[1]: All filesystems unmounted.
[    5.150577] systemd-shutdown[1]: Deactivating swaps.
[    5.151939] systemd-shutdown[1]: All swaps deactivated.
[    5.153221] systemd-shutdown[1]: Detaching loop devices.
[    5.154782] systemd-shutdown[1]: All loop devices detached.
[    5.156258] systemd-shutdown[1]: Stopping MD devices.
[    5.157540] systemd-shutdown[1]: All MD devices stopped.
[    5.158913] systemd-shutdown[1]: Detaching DM devices.
[    5.160292] systemd-shutdown[1]: All DM devices detached.
[    5.161706] systemd-shutdown[1]: All filesystems, swaps, loop devices, MD devices and DM devices detached.
[    5.164863] systemd-shutdown[1]: Syncing filesystems and block devices.
[    5.166903] systemd-shutdown[1]: Rebooting.
[    5.169679] reboot: Restarting system
[    5.170618] reboot: machine restart
```

Yup.

**Comment by bgilbert** [comment]
Added comment.

**Review by jlebon — APPROVED** [review]

**Comment by dustymabe** [comment]
Thanks @bgilbert!
