### PR TITLE
coreos-growpart: avoid creating ambivalent filesystems

### LINKED ISSUE #500: Installing over existing zfs causes resized sysroot to not be recognized by blkid
Copying and detailing from [discussion board post](https://discussion.fedoraproject.org/t/installer-not-creating-xfs-on-sda4/20141) as requested. Happy to provide any information on this machine or provisioning details.

I'm provisioning with PXE, and it's not working on a new machine. Error:

```
:/usr/libexec# journalctl -u ignition-ostree-growfs|cat
-- Logs begin at Tue 2020-05-26 20:50:08 UTC, end at Tue 2020-05-26 20:50:59 UTC. --
May 26 20:50:52 localhost.localdomain systemd[1]: Starting Ignition OSTree: Grow root filesystem...
May 26 20:50:52 localhost.localdomain coreos-growpart[702]: CHANGED: partition=4 start=1050624 old: size=4540383 end=5591007 new: size=15627002511 end=15628053135
May 26 20:50:52 localhost.localdomain coreos-growpart[702]: /usr/libexec/coreos-growpart: line 30: TYPE: unbound variable
May 26 20:50:52 localhost.localdomain systemd[1]: ignition-ostree-growfs.service: Main process exited, code=exited, status=1/FAILURE
May 26 20:50:52 localhost.localdomain systemd[1]: ignition-ostree-growfs.service: Failed with result 'exit-code'.
May 26 20:50:52 localhost.localdomain systemd[1]: Failed to start Ignition OSTree: Grow root filesystem.
```

This is because `/usr/libexec/coreos-growpart` is expecting `blkid -o export /dev/sda4` to print something that will set TYPE. But it doesn't:

```
:/usr/libexec# bash -ex ./coreos-growpart /sysroot
+ set -euo pipefail
+ path=/sysroot
+ shift
++ findmnt -nvr -o SOURCE /sysroot
++ tail -n1
+ src=/dev/sda4
++ findmnt -nvr -o MAJ:MIN /sysroot
++ tail -n1
+ majmin=8:4
++ realpath /sys/dev/block/8:4
+ devpath=/sys/devices/pci0000:00/0000:00:01.0/0000:02:00.0/host10/target10:0:0/10:0:0:0/block/sda/sda4
++ cat /sys/devices/pci0000:00/0000:00:01.0/0000:02:00.0/host10/target10:0:0/10:0:0:0/block/sda/sda4/partition
+ partition=4
++ dirname /sys/devices/pci0000:00/0000:00:01.0/0000:02:00.0/host10/target10:0:0/10:0:0:0/block/sda/sda4
+ parent_path=/sys/devices/pci0000:00/0000:00:01.0/0000:02:00.0/host10/target10:0:0/10:0:0:0/block/sda
++ basename /sys/devices/pci0000:00/0000:00:01.0/0000:02:00.0/host10/target10:0:0/10:0:0:0/block/sda
+ parent_device=/dev/sda
+ growpart /dev/sda 4
NOCHANGE: partition 4 is size 15627002511. it cannot be grown
+ true
++ blkid -o export /dev/sda4
+ eval
+ case "${TYPE}" in
./coreos-growpart: line 30: TYPE: unbound variable
:/usr/libexec# blkid -o export /dev/sda4
:/usr/libexec# blkid
/dev/sda1: LABEL="boot" UUID="1f3e305e-bc3c-4630-ad48-fc16be2872f0" TYPE="ext4" PARTLABEL="boot" PARTUUID="ff72fc91-4b8a-4dfe-84fe-9922f57bde8a"
/dev/sda2: SEC_TYPE="msdos" LABEL_FATBOOT="EFI-SYSTEM" LABEL="EFI-SYSTEM" UUID="307B-73FD" TYPE="vfat" PARTLABEL="EFI-SYSTEM" PARTUUID="7ef8e328-4fd5-410e-8caf-a5133d714ae0"
/dev/sda3: PARTLABEL="BIOS-BOOT" PARTUUID="a2ed3dff-acd1-49ae-a45e-63231fac1823"
:/usr/libexec#
```

At the very least I feel like `coreos-growpart` ought to set `TYPE=unknown` before the call to `blkid` so the error message makes a little more sense.

Files (not attaching included ignition configs, since we don't get to the stage where those are pulled):

---

boot.ipxe
```
#!ipxe

echo ===
echo === Booting Fedora CoreOS stable
echo ===

  # ipxe squashes spaces
  echo === -= Installing! =-
  echo ===
  echo === ........... machine: sponge
  echo === ................ OS: fcos stable
  echo === ....... personality: kube
  echo === .... install device: /dev/sda

  kernel /assets/fcos/stable/kernel  initrd=initrd console=tty0 console=ttyS0,115200n1 ip=dhcp rd.neednet=1 coreos.inst.install_dev=/dev/sda coreos.inst.ignition_url=http://10.28.0.1:2880/fcc/fcos/base.yaml?serial=4M5BGB2 coreos.inst.image_url=http://10.28.0.1:2880/assets/fcos/stable/raw.xz

initrd /assets/fcos/stable/initrd

boot
```

---

`curl http://10.28.0.1:2880/fcc/fcos/base.yaml?serial/4M5BGB2 | jq .`

```
{
  "ignition": {
    "config": {
      "merge": [
        {
          "source": "http://10.28.0.1:2880/fcc/fcos/secrets.yaml?serial=4M5BGB2"
        },
        {
          "source": "http://10.28.0.1:2880/fcc/fcos/personality/kube.yaml?serial=4M5BGB2"
        }
      ]
    },
    "version": "3.0.0"
  },
  "passwd": {
    "users": [
      {
        "name": "core",
        "sshAuthorizedKeys": [
          "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQT2eyuee5pHmDV91w7fLRk5Hz4hu9OjAZVT+h+4gAW/7l/91qTz79xocQA696Jk4mUJqMi9F3Jz1b+qsN99ukOxyISI861Gd+lg9g27r3GeVpssV2b+vOzZ5kLsojtu5UeTN/g3TvSj3xqVJIcN44RIF5565rEm0Dgntket81+Ke1IhGYxU41T58P66L3k8sMS9I7kSVFpblCKqikjUsVFxrTZBDFJLRsJygXzE8Fnot4LHqO1TDUs+DtlbGrsoth06xa1uslT+9Ah4PQNVmjE+N1ebK5yM9KOLpfAh+EOkihnmH0FG30JblNOFQ/K7Hkg84ogwOV5je9QlUESdnT arcs-sre",
          "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCniIiQ8E8825D0OWLoBCeJX3ygM+PKQZXfFUcJvRUtt1LlmVTdz8Lsz1Ih0EPkISkRvZ2NSuoZ9mX/66GsJOxEmhI+032xo8kKyfhWbLBx+SS5PKm6DFHB5yQruKsR2SHHvS4oEG7CZCJ2t6jou/eYkU8RYz3CvGpE5BrjBbGwoh+KE7z0mJDKXEUAbNS57G0Sq2RkAEL1Q+E6/v41zv1ZSM/r/pgCl+9GEeOBjNhmGRT30dB/bATmQ5e1DX4pPzJWApIU4d5ttbg+4UlNwTa0PYpclvm3z0ew51rlz/BVcdODlcXzTO9qjzZ9op8+VHOCwKGJJhNXswWoCKE7dRd grace@cerberus",
          "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCYQZKB9kxEYlst9Y7jpC6S5lH0yP83V6gSnEPuWl6w9AMJqdlUzj4LE8Zi/8I5DO8wNOtbGsyfDPYiFjIhFMRLEIUZbRrZyjwtR9otQSwx6qlXF2vz8gsWBTIr3G/IaGENCMLqDrkW2CYWKKluMWSY+rSSdIgmG7MHh13OUEFPf7ohvikDVVWBxlnwkI2n8zEhWAkO4WJW1J0KG+IUhxPJHynnyNcULU1u6pjZpxp8+x84GkrJv3M8DP9OLxxwFfA+2mYVbVXRvNZNXaVUq1eXapqEO6l8lyGUCfcmME3wo4UaX6VuCjXiKdd2XKrkcYitJE+pl6czgy+GfVIn01NFaykWB4p2J/g6iRlYGvHHjEpM7uT72gWz1h159f+h5B0p7iBWIGubUrRstisag2lM4DDelEYL689LH6VBswcVXA9XVuEdt1BzIU92INQ7zFDfRak/pRVtmu9H0dUdf7nZ8/9VBq5QabYbvQpNF0wZ58Vb+KVNjAREoTv5w22dKIpXPaFbBASeOg2zVilxUtrTEucxsiJDkrgGYlX0Uq2f+kjBkZF9iu9kz6OkxXH+vFuLUn4ZldtqvMr/S2Vjdd8KDyLVezMaXw4fqyRZ59A1Ynx6SvglJkFPVRTMRjDJ783YP/zuGkceP9qnMVF8qk2fCYFulzcilS2IapXgswvhOw== wernicke@lanl.gov",
          "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCwc6FkQ0QKx0Mk/7/feRsx29N4pKfbkkVwq8LR03/vlcZlinxNY5PWmJnDUsMzi/YjzU0HphLl4HxF3vuGMC7xr2z0OhumjQXi7GSvaX8vgYG10eVus7cvu9jScMD77Usx06JZj5FU43Vg2Y8sfrlk7Bk4L0NkQM+mlPn9iGhFIchhJL2EcdNU62rPuGvzfn3npudYNt06sXA8Tl2ur5sk9QNtev2qB0rvv6NtV8T2/ujdPlyYpZUP+eHCghCak9qeYYfhxr8g+NIuDZ8oMVsi8m2i2n5dd/PWRuOTaQvordioQJ/bIss0opr/z1o71Z+jtnlpFlaaTRsl+gbLZKzP neale@cfl",
          "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVhzx0bl8rvK2h58y/WK3men1AVT7lH2UwiiAxMy9XMfufdSznYl6zJQ+UCByprJy17SqQIkJGUNYAnegirzAEaqbHKFgRQijVwAGcOQ2VU55jxK8WB1TF5alA+m4y+xwHdsiIJVW5CvWSS0a+E5rPV5ssg6ScWp+FAiDoffJxapjPa17aXQ6c2x3hx+SD1D1DJavgxbOjeXplkNUBGVu+wFlO5a43f5UDA3ydNMmAaK9SHJ3uQWBnYEfAG0KDCcxwHVTUHorXlgb/yEYjwtFIbtWQackvD6yZQpGhYujTQ2oHYX/WGzFHedUQAk9owgvimOAIu5aGoLGckXQVmdDH heather@waffles",
          "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC0PISbvPqoO3SmRoAjAZT5ZrglVo3v+r1aykjhwX1GN vchu"
        ]
      }
    ]
  },
  "storage": {
    "files": [
      {
        "path": "/etc/hostname",
        "contents": {
          "source": "data:,sponge%0A"
        },
        "mode": 420
      },
      {
        "path": "/usr/local/sbin/ipmi",
        "contents": {
          "source": "data:,%23!%20%2Fbin%2Fsh%0A%0Aif%20%5B%20%24(id%20-u)%20-ne%200%20%5D%3B%20then%0A%20%20echo%20%22ERROR%3A%20Try%20that%20again%20as%20root.%22%201%3E%262%0A%20%20exit%201%0Afi%0Apodman%20run%20--rm%20-it%20--privileged%20--device%20%2Fdev%2Fipmi0%20arcs.lanl.gov%2Fprod%2Fipmitool%20%22%24%40%22%0A"
        },
        "mode": 493
      },
      {
        "path": "/etc/NetworkManager/system-connections/mgmt",
        "contents": {
          "source": "data:,%5Bconnection%5D%0Aid%3DManagement%20Network%0Atype%3Dethernet%0A%0A%5Bethernet%5D%0Amac-address%3D24%3A6e%3A96%3A11%3Aa7%3A64%0A%0A%5Bipv4%5D%0A%0Amethod%3Dmanual%0A%0Aaddress0%3D10.28.1.102%2F20%0A%0Adns%3D10.28.0.1%0Adns-search%3Dmgmt%0A%0A%0A%5Bipv6%5D%0Amethod%3Dauto%0A"
        },
        "mode": 384
      },
      {
        "path": "/etc/NetworkManager/system-connections/lanl",
        "contents": {
          "source": "data:,%5Bconnection%5D%0Aid%3DLANL%20Network%0Atype%3Dethernet%0A%0A%5Bethernet%5D%0Amac-address%3D24%3A6e%3A96%3A11%3Aa7%3A65%0A%0A%5Bipv4%5D%0A%0Amethod%3Dmanual%0A%0Aaddress0%3D128.165.37.161%2F24%0A%0Agateway%3D128.165.37.241%0A%23Disabled%20until%20we%20figure%20out%20how%20to%20get%20NetworkManager%20to%20be%20smarter%20about%20which%20nameservers%20to%20use%0A%23dns%3D128.165.4.4%3B128.165.4.33%0A%0A%0A%5Bipv6%5D%0Amethod%3Dauto%0A"
        },
        "mode": 384
      },
      {
        "path": "/etc/systemd/system.conf.d/10-default-env.conf",
        "contents": {
          "source": "data:,%5BManager%5D%0ADefaultEnvironment%3Dhttp_proxy%3Dhttp%3A%2F%2Fproxyout.lanl.gov%3A8080%20https_proxy%3Dhttp%3A%2F%2Fproxyout.lanl.gov%3A8080%20no_proxy%3Dlocalhost%2C.lanl.gov%2C.mgmt%2C10.28.0.1%20NO_PROXY%3Dlocalhost%2C.lanl.gov%2C.mgmt%2C10.28.0.1%2C10.0.0.0%2F8%2C128.165.0.0%2F16%0A"
        },
        "mode": 420
      },
      {
        "path": "/etc/profile.d/lanl-env.sh",
        "contents": {
          "source": "data:,http_proxy%3Dhttp%3A%2F%2Fproxyout.lanl.gov%3A8080%0Ahttps_proxy%3Dhttp%3A%2F%2Fproxyout.lanl.gov%3A8080%0Ano_proxy%3Dlocalhost%2C.lanl.gov%2C.mgmt%2C10.28.0.1%0ANO_PROXY%3Dlocalhost%2C.lanl.gov%2C.mgmt%2C10.28.0.1%2C10.0.0.0%2F8%2C128.165.0.0%2F16%0Aexport%20http_proxy%20https_proxy%20no_proxy%20NO_PROXY%0A"
        },
        "mode": 420
      },
      {
        "path": "/etc/sudoers.d/lanl-proxy",
        "contents": {
          "source": "data:,Defaults%20env_keep%20%2B%3D%20%22http_proxy%22%0ADefaults%20env_keep%20%2B%3D%20%22https_proxy%22%0ADefaults%20env_keep%20%2B%3D%20%22no_proxy%22%0ADefaults%20env_keep%20%2B%3D%20%22NO_PROXY%22%0A"
        },
        "mode": 420
      },
      {
        "overwrite": true,
        "path": "/etc/krb5.conf",
        "contents": {
          "source": "data:,%5Blibdefaults%5D%0A%20%20default_realm%20%3D%20lanl.gov%0A%20%20allow_weak_crypto%20%3D%20true%0A%20%20forwardable%20%3D%20true%0A%0A%5Brealms%5D%0A%20%20lanl.gov%20%3D%20%7B%0A%20%20%20%20kdc%20%3D%20kerberos.lanl.gov%0A%20%20%20%20kdc%20%3D%20kerberos-slaves.lanl.gov%0A%20%20%20%20admin_server%20%3D%20kerberos.lanl.gov%0A%20%20%7D%0A%0A%5Bdomain_realm%5D%0A"
        },
        "mode": 420
      },
      {
        "path": "/var/lib/textfile/README.md",
        "contents": {
          "source": "data:,Files%20in%20this%20directory%20ending%20in%20%60.prom%60%0Awill%20be%20added%20to%20metrics%20by%20the%20Prometheus%20node%20exporter.%0A"
        },
        "mode": 420
      },
      {
        "path": "/var/opt/mount-check.sh",
        "contents": {
          "source": "data:,%23!%2Fbin%2Fsh%0A%0AFILE%3Dis.mounted%0Awhile%20true%3B%0Ado%0A%20%20%20%20for%20DIR%20in%20%24(ls%20%2Fetc%2Fsystemd%2Fsystem%20%7C%20grep%20%22%5C.mount%22%20%7C%20sed%20's%2F.mount%2F%2F'%20%7C%20sed%20's%2F%5E%2F%5C%2F%2F'%20%7C%20sed%20's%2F%5C-%2F%5C%2F%2Fg')%0A%20%20%20%20do%0A%20%20%20%20%20%20%20if%20test%20-f%20%22%24DIR%2F%24FILE%22%0A%20%20%20%20%20%20%20then%0A%20%20%20%20%20%20%20%20%20%3A%20echo%20%22%24DIR%20exists%22%0A%20%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%20%20echo%20%22Restarting%20necessary%20mounts%3A%20%24DIR%22%0A%20%20%20%20%20%20%20%20%20%20sudo%20systemctl%20restart%20%24DIR%0A%20%20%20%20%20%20%20fi%0A%20%20%20%20done%0A%20%20%20%20sleep%2030s%0Adone%20%20%20%20%20%20%20%20%20%20%0A"
        },
        "mode": 493
      }
    ]
  },
  "systemd": {
    "units": [
      {
        "contents": "[Unit]\nDescription=Prometheus Node Exporter\nAfter=docker.service\nAfter=network-online.target\n\n[Service]\nEnvironment=IMAGE=prom/node-exporter:latest\nExecStartPre=-/usr/bin/podman rm -fi %p\nExecStartPre=/usr/bin/podman pull ${IMAGE}\nExecStart=/usr/bin/podman run --name %p --net=host --volume /:/host:ro,rslave --volume /var/lib/textfile:/textfile --publish 10.28.1.102:9100:9100 ${IMAGE} --path.rootfs /host --collector.textfile.directory /textfile\nExecStop=/usr/bin/podman stop %p\nRestart=always\nRestartSec=5\n\n[Install]\nWantedBy=multi-user.target\n",
        "enabled": true,
        "name": "node-exporter.service"
      },
      {
        "contents": "[Unit]\nDescription=Mount check\nAfter=network-online.target\n\n[Service]\nExecStart=/bin/sh -c '/opt/./mount-check.sh'\nRestart=on-failure\n\n[Install]\nWantedBy=multi-user.target\n",
        "enabled": false,
        "name": "mount-check.service"
      },
      {
        "contents": "[Unit]\nDescription=Prometheus Dell Hardware Exporter\nAfter=docker.service\nAfter=network-online.target\n\n[Service]\nEnvironment=IMAGE=galexrt/dellhw_exporter:latest\nExecStartPre=-/usr/bin/podman rm -fi %p\nExecStartPre=/usr/bin/podman pull ${IMAGE}\nExecStart=/usr/bin/podman run --name %p --publish 10.28.1.102:9137:9137 --privileged ${IMAGE}\nExecStop=/usr/bin/podman stop %p\nRestart=always\nRestartSec=5\n\n[Install]\nWantedBy=multi-user.target\n",
        "enabled": true,
        "name": "dellhw-exporter.service"
      }
    ]
  }
}
```

---
If reporting a bug in Fedore CoreOS, please include the
output of `rpm-ostree status`.

```
:/root# rpm-ostree status
sh: rpm-ostree: command not found
```

;)

### PR DESCRIPTION
**Pull request by bgilbert**
If `blkid` finds a partition containing superblocks from multiple filesystem types, it'll refuse to report anything about that partition.  If we `growpart` `/sysroot` into space that was previously used by ZFS, we'll pick up a ZFS superblock and then fail to detect the filesystem type for resizing.

Fix this by probing the filesystem type before running `growpart`.  After running `growpart`, but before resizing, run `wipefs(8)` on the newly-grown partition, asking it to delete all superblocks for filesystem types other than the one we just detected.

This is kind of hacky.  We can't guarantee that `wipefs` will only touch the unwritten space past the end of the existing filesystem.  Presumably the existing filesystem contents are safe (either they come from an image, or Ignition has just created the filesystem), but there's no guarantee that `wipefs` won't detect an errant superblock signature and thus modify the filesystem while it's mounted.  Of course, in that case we'd already have an ambivalent filesystem and thus it wouldn't mount properly in the future anyway.

Also exit early if the filesystem type is unrecognized.

Includes https://github.com/coreos/fedora-coreos-config/pull/429.  Fixes coreos/fedora-coreos-tracker#500.

### CODE REVIEW

File: overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart [hunk 1]
```diff
@@ -15,6 +15,16 @@ shift
...
 src=$(findmnt -nvr -o SOURCE "$path" | tail -n1)
 
+# Get the filesystem type before extending the partition.  This matters
+# because the partition, once extended, might include leftover superblocks
+# from the previous contents of the disk (notably ZFS), causing blkid to
+# refuse to return any filesystem type at all.
+eval $(blkid -o export "${src}")
+case "${TYPE:-}" in
+    xfs|ext4) ;;
+    *) echo "error: Unsupported filesystem for /sysroot: ${TYPE:-}" 1>&2; exit 1 ;;
```
Comment (dustymabe) [inline overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart]: Since @jlebon had made a comment over in https://github.com/coreos/fedora-coreos-config/pull/429#discussion_r431142673 I applied his change to my PR. Do you want to pick up that change or would you like to just apply it on top of what you have here (or we could merge the other PR and you rebase)?

File: overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart [hunk 2]
```diff
@@ -15,6 +15,16 @@ shift
 # this shouldn't happen for us but we're being conservative.
 src=$(findmnt -nvr -o SOURCE "$path" | tail -n1)
 
+# Get the filesystem type before extending the partition.  This matters
```
Comment (dustymabe) [inline overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart:18]:
```suggestion
# Get the filesystem type before extending the partition. This matters
```

or was the two spaces intentional?

File: overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart (hunk 1 above)
Comment (dustymabe) [reply overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart]: Also feel free to just squash everything down into a single commit. I'm not worried about my commit too much.

File: overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/module-setup.sh [hunk 3]
```diff
@@ -25,18 +25,19 @@ install() {
...
+        growpart   \
+        realpath   \
+        resize2fs  \
+        tail       \
+        touch      \
+        xfs_growfs \
+        wipefs
 
     # growpart deps
     # Mostly generated from the following command:
```
Comment (dustymabe) [inline overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/module-setup.sh:43]: do you mind removing the tabs from the below block of code. That was my bad.

**Review by dustymabe — APPROVED** [review]
A few comments.. Otherwise LGTM

File: overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart (hunk 2 above)
Comment (bgilbert) [reply overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart:18]: I still believe in two spaces between sentences.  :grin:  Possibly because I work in monospace so much...

File: overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart (hunk 1 above)
Comment (bgilbert) [reply overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart]: I think it's cleaner to keep the changes separate.  Rebased onto the updated commit.

**Comment by bgilbert** [comment]
Updated.  Dropped tabs, and also fixed another hardcoding of `/sysroot`.

File: overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart [hunk 4]
```diff
@@ -46,13 +56,15 @@ else
...
-eval $(blkid -o export "${src}")
+# Wipe any filesystem signatures from the extended partition that don't
+# correspond to the FS type we detected earlier.
+wipefs -af -t "no${TYPE}" "${src}"
+
 # TODO: Add XFS to https://github.com/systemd/systemd/blob/master/src/partition/growfs.c
 # and use it instead.
 case "${TYPE}" in
-    xfs) xfs_growfs /sysroot ;;
+    xfs) xfs_growfs "${path}" ;;
```
Comment (dustymabe) [inline overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart:66]: I wonder if there was a historical reason for hardcoding it to `/sysroot` here.

**Comment by dustymabe** [comment]
still LGTM - will give others a chance for review.

File: overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart [hunk 5]
```diff
@@ -46,13 +56,15 @@ else
     growpart "${parent_device}" "${partition}" || true
 fi
 
-eval $(blkid -o export "${src}")
+# Wipe any filesystem signatures from the extended partition that don't
+# correspond to the FS type we detected earlier.
+wipefs -af -t "no${TYPE}" "${src}"
```
Comment (cgwalters) [inline overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart:61]: Huh, clearly `wipefs` has been used for this before.  The `-t no${TYPE}` bit is so...specific to exactly what we need!

Comment (cgwalters) [reply overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart:61]: One lingering concern though.  Does `wipefs` somehow understand how to avoid any content inside actual files?  Like what if we happened to have a *file* that has something that resembles a ZFS header?

**Review by cgwalters — APPROVED** [review]

File: overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart (hunk 5 above)
Comment (cgwalters) [reply overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart:61]: I guess the fact that this code should only run inside the initramfs, before any user data could have been written mostly ameliorates that concern.

Comment (bgilbert) [reply overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart:61]: If there's a file that looks like a ZFS header, we lose; see the third paragraph of the PR description.  It's not ideal.

Comment (cgwalters) [reply overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart:61]: OK yeah.  So to do this truly robustly would be something like teaching `wipefs` how to query the filesystem as to whether a specific area it was going to overwrite was part of an allocated block.  I think XFS can make that efficient...though efficiency doesn't matter much.

I'm OK with this as is but it does leave me with the lingering feeling like this *might* explode somehow later...

**Comment by cgwalters** [comment]
One other thought here...is there some way we can tell the kernel/udev that certain signatures should "win"?  In our case we have e.g. a GPT partition with standard XFS signatures, I feel like it's almost a zfs-fuse bug if it's doing something like scanning the whole block device and not looking for and deferring to well-formed headers from existing well-known filesystems like ext4/xfs/btrfs etc.

File: overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart (hunk 5 above)
Comment (bgilbert) [reply overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/coreos-growpart:61]: It might be cleaner to teach wipefs to only touch a specific range of disk blocks (the ones from the expanded part of the partition).  Technically this could be done now with a wrapper script, but that seemed overly ambitious.

**Comment by bgilbert** [comment]
`mount -t auto` defers to `libblkid`.  udev presumably defers to `blkid`.  And `libblkid` declines to pick favorites; depending on which API you use, it'll either tell you nothing or give you a list of all detected filesystems.  I don't agree with that design, but it's been there since 2009.
